ALTER TABLE documents ADD COLUMN IF NOT EXISTS field TEXT NOT NULL DEFAULT '일반';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS views BIGINT NOT NULL DEFAULT 0;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS field TEXT NOT NULL DEFAULT '일반';
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
